### ISSUE TITLE
Instability on Insert Effects

### ISSUE THREAD

**Issue by badosu** [zynaddsubfx/zyn-fusion-issues#112]
I bought fusion some months ago and started tinkering with it these days.

I am having lots of crashes mostly related to effects, these seem to happen when:

- Deleting an effect, specially if it's before others in the chain
- Changing an effect type
- Simply focusing the interface on the effects section

This is making zyn-fusion unusable for me, using 3.0.2 on Manjaro (Arch) with Ardour.

**Comment by fundamental** [comment]
Can you confirm which version you downloaded from gumroad? This sounds similar to a bug which was already fixed in the 3.0.2-patch4 version and today I'm going to have the patch5 version uploaded to gumroad as a brief holdover while the release notes for 3.0.3 are assembled.

EDIT: -patch5 should be up this weekend due to a rather busy day today

**Comment by badosu** [comment]
I downloaded `3.0.2-release`, gonna give `patch4` a try and report back.

**Comment by fundamental** [comment]
Thanks

**Comment by badosu** [comment]
Seems like an older version issue indeed, thanks for the clarification!
