### ISSUE TITLE
ADDsynth voice Copy/Paste not working?

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#123]
I tried this during my Sonoj talk, and now I tried again - I think the voice Copy/Paste functionality in ADDsynth doesn't work right now.

Can anyone confirm this?

![image](https://user-images.githubusercontent.com/491704/32699685-f0329d84-c7b9-11e7-8c2b-87905160dc3f.png)

**Comment by theofficialajyoung** [comment]
I can confirm this. I reported it in the KVR Forum, but this is probably a better place for bug reporting.
Currently using the Windows VST demo.

**Comment by fundamental** [comment]
I just tried it on the development build and it looks like it is fixed. Since I'm back to working on pushing out the 3.0.3 release I'll leave this open for the bug to be confirmed fixed. If it's not confirmed the steps that I used to verify that copy/paste is working were:

1. open zyn-fusion in standalone mode
2. go to add synth
3. go to voice
4. change volume
5. hit copy
6. change voice
7. acknowledge volume is at the default level
8. click paste
9. observe volume changed to the value seen in step 4

**Comment by theofficialajyoung** [comment]
Looking at the KVR thread a little closer:
http://www.kvraudio.com/forum/viewtopic.php?f=47&t=488363&start=60#p6851556
 it appears you may have fixed this already, it's just not yet in a version available to the public.
