### ISSUE TITLE
ZynFusion doesn't die after closing the main window

### ISSUE THREAD

**Issue by suhr** [zynaddsubfx/zyn-fusion-issues#17]
This is a proper behaviour for a plugin but not for a standalone synth.

**Comment by unfa** [comment]
I can confirm this.
The synth engine is still working and playing notes after closing the UI window.

This also sometimes happens when the UI crashes, but the synth is still working in headless mode.
(My head exploded! Well, who cares, we'll play this gig till the end anyway, baby!)
I consider this a good thing - but maybe the UI could re-run itself and update in such a case?

**Comment by fundamental** [comment]
Fixed, expect the new build soon
