### ISSUE TITLE
no midi input

### ISSUE THREAD

**Issue by phil123456** [zynaddsubfx/zyn-fusion-issues#244]
on a rPI4

I use jack and zynaddsubfx was working fine

now I just compiled zyn-fusion , it has no midi input at all

I click on midi , nothing happens except "use ctrl to enable midi learn" witch does not do anything and learn is just below

it's not reacting to midi at all

is there any tutorial ? how does this works ?

**Comment by fundamental** [comment]
Technically midi/audio backends can be set at runtime (post-startup), but since I got the impression that I was the only one using that functionality it's not directly exposed in the zyn-fusion GUI. You can set the MIDI backend at startup with `zynaddsubfx -I  BACKEND` e.g. `zynaddsubfx -I ALSA` or `zynaddsubfx -I JACK`. The same can be done with the audio output with '-O'.

At compile time the various input/output combinations are selected and defaults are baked into the binary. I'm guessing that the default one that you built is `zynaddsubfx -I ALSA -O JACK` and may want to have instead `zynaddsubfx -I JACK -O JACK`.

Let me know if you need more info.

**Comment by phil123456** [comment]
I did -I jack -O jack but no midi comes in
the UI's not really obvious to use...I was expecting something more intuitive

**Comment by fundamental** [comment]
Sounds like zyn's MIDI is working as expected, but it isn't connected to any other program. I'd recommend looking at the connections available within qjackctl. The same connections can be managed via the command line (jack_connect/aconnect), but I'd recommend qjackctl for an easier to get started way.

**Comment by phil123456** [comment]
ok I managed to make it work
thanks
