### ISSUE TITLE
[question] where can I find addsynth / voice parameters / unison in new GUI?

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#255]
Where can I find this part where he is editing 'unison'?
https://youtu.be/XNkUQhU7SZs?t=218
![unison](https://user-images.githubusercontent.com/378249/101262867-e176e700-3741-11eb-8cfc-1de29a987115.png)

I find it add 'modulation', but in the youtube video that seems to be turned off. I'm somewhat confused here.

**Comment by fundamental** [comment]
So, unison operates independently of modulation, but it is grouped into modulation in the new GUI. The choice was made by the designer and there's not really a better place that I know of to put it given the constraints of the new UI. Since changing this would be more of a large scale design issue not likely to change I'm going to close this.

If there's some suggestions for how to tweak the presentation to better hint that unison works with or without the FM/PM/AM/etc modulation feel free to reopen (I think issue creators have that ability on github).

**Comment by grammoboy2** [comment]
I'm trying to replicate this guitar sound by P. Nasca. I'm a Zyn newbie (as in sound design), but I've a hard time replicating that sound :)
https://www.youtube.com/watch?v=XNkUQhU7SZs

see also 
https://github.com/zynaddsubfx/zyn-fusion-issues/issues/254

Maybe someone else can do it. Challenge!

**Comment by grammoboy2** [comment]
First thought would be, 'why not add another tab'? But my understanding of Zynaddsubfx is not well enough at the moment. I'll keep it in the back of my mind for later maybe.

**Comment by fundamental** [comment]
Well, per adding another tab, it's a fine thing to do, but there needs to be enough content for said tab otherwise visually things will look rather bad. Unison is an important feature, but not one with a lot of controls.

**Comment by grammoboy2** [comment]
Another quick thought, is to use colors, which indicate the different parts that belong to each other. I'm looking at the open tab and have no idea what belongs to modulation and what not atm.

**Comment by fundamental** [comment]
Reopened upon request.

**Comment by grammoboy2** [comment]
A more broadly feedback here, which also mention the place of 'unison'.
https://github.com/zynaddsubfx/zyn-fusion-issues/issues/259

Closing this one.
