### ISSUE TITLE
[question/ feature request] Possible to install old and new interface together?

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#256]
Hi,
I would like to install both the new and old interface. Is that possible?

If not, then I would make a feature request.

Thx

**Comment by fundamental** [comment]
It's possible, but not an officially supported use case. Both the fusion and fltk/ntk based user interface can be run as remote processes zyn-fusion and zynaddsubfx-ext-gui (fltk/ntk) are GUI processes which just need the OSC URL of the backend to be connected. It is even possible to have both of them connected at once (though do expect the occasional quirk since the number of people doing so likely can be counted on one hand).

I do not think it would be wise to complicate the already messy build process by introducing full support for both simultaneously, but feel free to have both GUI processes installed on your system.

**Comment by grammoboy2** [comment]
Maybe ignorance from my side, but couldn't this be solved by naming the 
binaries and such of zyn-fusion, zyn-fusion instead of zynaddsubfx?

And the make clear in the interface of zyn-fusion, that people are 
working with zyn-fusion slash zynaddsubfx. So explicitly also using/ 
referring to the name zynaddsubfx?

**Comment by fundamental** [comment]
Common binaries:
  - 'zynaddsubfx' - the thing which has all the audio code aka the backend, commonly headless. Previously this also embedded the ntk/fltk GUI. Now it just launches a child process for 'zyn-fusion'.
  - 'zynaddsubfx-ext-gui' - just the GUI based on the older fltk/ntk interface. no audio code here
  - 'zyn-fusion' - just the GUI based on the new fusion design using mruby-zest under the hood. no audio code here
  - 'oscprompt' - command line OSC client, no audio code here
  - 'osc_send'/'oscsend' - tools for sending OSC to backends like 'zynaddsubfx'

Hope that clarifies the previous description since some of these terms are somewhat overloaded.
