### ISSUE TITLE
Please consider a release

### ISSUE THREAD

**Issue by magnetophon** [zynaddsubfx/zyn-fusion-issues#265]
The [latest release](https://github.com/zynaddsubfx/zynaddsubfx/releases/tag/3.0.5) is from april 2019 and at this moment there have been 350 commits to master.
A new release would be most welcome!  :)

**Comment by fundamental** [comment]
Totally agreed.
In terms of the release process I've gone through the git logs to build
up a change log.
I have to give them a second pass to make sure everyone gets documented
in the AUTHORS.txt file (in the past I've been better at maintaining
that during development, but I want it to be up-to-date at the time of a
release).

I'm currently trying to make sure it's safe to update the version of the
MRuby interpreter used within the fusion GUI. There were a few quirks,
but at least running the GUI not connected to any backend it looks like
it works. This step is something that I'd like to avoid just prior to a
release, but well there's issues compiling if the system ruby version is
3.0.0. Not something I'd like to pass over to distro packagers.

I was hopeful that one user was looking into the crazy out-of-date
version of waf used for pugl and I tried to budget some time for that,
but that didn't end up happening over the past two weeks.

In terms of pull requests there's some real nice additional smoothing of
parameters to avoid some zipper noise (filter/volume). Those seem merge
ready prior to release.

The wavetable pull request is still in progress and is more of a large
scale change, so it might be good to have that in a developmental
version for a bit.

Updates to the build system are progressing, but incomplete. (shifting
over to docker)

Integration of an additional ladder filter is in progress, though unless
I'm mistaken there's still some work to be done on that one.

There's getting more of a need to groom the huge backlog of issues that
have built up across the different issue trackers. It seems like it
might be a wise idea to simplify the fusion repos instead of dealing
with the git submodules, have one set of issues which apply to internal
bugs, then close out the sourceforge issue tracker, and migrate
everything over to this issue-only repo.
I may solicit assistance for this on the zyn mailing list, but anyone
who is reading and interested in lending a hand would be great.
Prioritization is challenging.

On that front there's one NaN bug in the GUI which since there's
multiple users reporting and there's an ardour test it should likely be
an easy fix prior to release.

The original plan was to get out a -rc1 release along with the
linux-audio quarterly releases, but things have been dragging a bit.
Linux builds should be back to good soon enough. I think windows is
continuing without a problem (though there's always hosts with
under-documented issues). MacOS has all sorts of 'fun' with regards to
package signing and whatnot which we haven't been doing and given other
more pressing issues seems like a comparatively low priority.

**Comment by fundamental** [comment]
Resolved?
