### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by StoicIndividual** [zynaddsubfx/zyn-fusion-issues#278]
Operating system: Artix linux
Window manager: dwm
ardour version: 6.6.0

I'm not sure if this is the right place I should be asking for help, but I've been dealing with 2 issues:

1) Wrong window sizing

Zyn-fusion keeps opening with a window larger than the UI itself, I can resize it back to normal, so it seems to have minimum width and height but it'll only last for one ardour session

![pic-full-210310-2033-49](https://user-images.githubusercontent.com/44035542/110687524-e041d400-81e0-11eb-87ad-d3a63f1582e1.png)

2) Can't input text

even after clicking the keyboard icon at the top right I can't type or delete text, I can press and interact with ui elements though

![image](https://user-images.githubusercontent.com/44035542/110688582-0320b800-81e2-11eb-910e-75f73bc8e6de.png)

**Comment by StoicIndividual** [comment]
I accidentally had the vst plugin selected, both of these issues are fixed when using lv2

**Comment by fundamental** [comment]
> I accidentally had the vst plugin selected, both of these issues are fixed when using lv2

Interesting. Thanks for adding this information. The code under the hood is essentially the same with a few small hooks to work with either plugin spec. I can totally see some issues with resizing with the VST which would have been fixed in the LV2, but knowing that keyboard behavior differs between the two is news to me. That's super handy to know about since windows users are almost always on the VST.
