### ISSUE TITLE
Clicking / Punch sound when using Low Pass with resonance

### ISSUE THREAD

**Issue by VincyZed** [zynaddsubfx/zyn-fusion-issues#289]
Hi there!

I think that this is a bug, but let me know if that's not the case and what I need to do (what control to tweak) to get rid of it:

When using the Additive oscillator (with any waveform), and when applying either a Voice or Global **analog LP2 filter**, when setting the cutoff very low with some resonance (25% to 100%), there is an audible punch / click sound, as if a filter envelope had a very short upwards attack of some sort. I've messed with tons of controls and never found how to get rid of it.

I also tried a version that I compiled October of 2020, and it didn't do it, it sounded fine (no punch noise at all, it sounds as it should).

Here's an audio demo from the latest commit (or very close to) demonstrating this issue :
[Bug.zip](https://github.com/zynaddsubfx/zynaddsubfx/files/6910459/Bug.zip)

It seems that that small "envelope attack" starts approximatively from 50% cutoff and goes down to the cutoff value when it's below 50% and above when it goes above 50% (when cutoff is >50%, we hear it sort of opening up from that point extremely quickly instead).

I can confirm that only the Additive oscillator was active here and that all envelopes were disabled / flat and on their default position. Moving the attack time and value parameter did not fix the issue.

Let me know if there's anything I can do on my side for further testing. In the meantime, I'll be using that version I compiled last year as my daily driver.

Thank you for maintaining this wonderful synthesizer!

**Comment by fundamental** [comment]
Sounds like there's a bug in the filter interpolation code. There have been a few changes there in the past year, so that seems to fit the description.

**Comment by zynmuse** [comment]
I notice the same problem and it is a serious one in so far as any compositions using a filter made whilst this bug is present will sound quite different once the bug is fixed!

**Comment by fundamental** [comment]
Agreed, this sort of bug should be a release blocker. Basically the workflow for fixing it will be:

1) Automate generating audio for the target setting file
2) Bisect the code for when the behavior changes
3) Identify the exact commit which impacts the output
4) Fix the offending commit
5) Apply the fix to the current git HEAD

If anyone wants to take a stab at the bisecting and locating the exact code that would be helpful, though I should be able to get back to this issue before the next release.

**Comment by friedolino78** [comment]
> Hi there!
> 
> I think that this is a bug, but let me know if that's not the case and what I need to do (what control to tweak) to get rid of it:
> 
> When using the Additive oscillator (with any waveform), and when applying either a Voice or Global **analog LP2 filter**, when setting the cutoff very low with some resonance (25% to 100%), there is an audible punch / click sound, as if a filter envelope had a very short upwards attack of some sort. I've messed with tons of controls and never found how to get rid of it.
> 
> I also tried a version that I compiled October of 2020, and it didn't do it, it sounded fine (no punch noise at all, it sounds as it should).
> 
> Here's an audio demo from the latest commit (or very close to) demonstrating this issue :
> [Bug.zip](https://github.com/zynaddsubfx/zynaddsubfx/files/6910459/Bug.zip)
> 
> It seems that that small "envelope attack" starts approximatively from 50% cutoff and goes down to the cutoff value when it's below 50% and above when it goes above 50% (when cutoff is >50%, we hear it sort of opening up from that point extremely quickly instead).
> 
> I can confirm that only the Additive oscillator was active here and that all envelopes were disabled / flat and on their default position. Moving the attack time and value parameter did not fix the issue.
> 
> Let me know if there's anything I can do on my side for further testing. In the meantime, I'll be using that version I compiled last year as my daily driver.


can you make a demo with the same patch without the bug?

**Comment by friedolino78** [comment]
> Sounds like there's a bug in the filter interpolation code. There have been a few changes there in the past year, so that seems to fit the description.

first idea would be that the parameter interpolator state variables are preloaded with a generic value instead of the param value of the preset.
Code inspection shows AnalogFilter.cpp line 51:
`freq_smoothing.reset( freq * MAX_FREQ_CO );`
https://github.com/zynaddsubfx/zynaddsubfx/blob/2c8937521bf8566e04b9e31e2d54a049c9722f7d/src/DSP/Filter.cpp#L61

while freq being 1000Hz when the filter is constructed:
`filter = memory.alloc<AnalogFilter>(Ftype, 1000.0f, pars->getq(), Fstages, srate, bufsize);`
https://github.com/zynaddsubfx/zynaddsubfx/blob/2c8937521bf8566e04b9e31e2d54a049c9722f7d/src/DSP/Filter.cpp#L61

the parameter smoothing exhibits that problem. it existed before but was inaudible.

one pragmatic solution could be moving the reset of the smoothing out of the constructor of the filter to the first.
https://github.com/zynaddsubfx/zynaddsubfx/pull/136
first test with ears and spectrogram showed that the wideband noise at the start of a note is gone.

It is maybe not the perfect solution but could cure the problem that users get used to the wrong behaviour, if the final solution takes too long.

**Comment by zynmuse** [comment]
Thanks friedolino78.
The problem appears to be fixed in the current master.
As we suspected all the music I had produced while the problem was present now sounds bland.
The punch was contributing to the rhythm more than I had realized.
I probably need to try to put it back in using the filter envelope!
Actually the bug maybe worth a switch to enable / disable it on the filter display. It's probably as useful a feature as the punch time and strength settings on the global amplitude display.
I wonder if anyone else will miss it?

**Comment by VincyZed** [comment]
I can confirm that that fix does work indeed. Thank you!
@zynmuse This has happened to me in the past when they fixed a bug in Surge, I know how frustrating this can be.
That being said, I don't think adding more parameters to the already relatively crowded UI just to switch on a bug that can be reproduced using the Filter Envelope like you suggested is a good solution here. Since this has probably affected the vast minority of users, adding controls to replicate it wouldn't serve any good to the users in general IMO.

Thanks for confirming the bug and testing :)

**Comment by friedolino78** [comment]
I also think it makes more sense to realize the desired behavior via envelope. Maybe we (you) can figure out the needed attack time and value for others who may ask for it in the future.

**Comment by zynmuse** [comment]
I'm not certain either.
However some of the best ideas come for accidents!
