### ISSUE TITLE
Add master volume control in mixer view

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#44]
See title

**Comment by fundamental** [comment]
Here's one possible implementation. I'm not too happy with how it looks, though I'm not quite sure how to tidy it up.
![zyn-fusion-mixer-master-vol](https://cloud.githubusercontent.com/assets/766621/20650805/5d06ece0-b4a5-11e6-978f-63569c5a0a5b.png)

**Comment by fundamental** [comment]
@budislav Do you have any opinions about adding this extra VU meter + volume slider in the mixer view?

**Comment by budislav** [comment]
@fundamental thank you for asking me for this. Since I designed everything, it is good (necessary) to ask me for help with every UX/UI change. I will try to make this good but I have some questions about UI.

In the old Zyn we could compile synth with more than 16 channels. That's why I put scroll bar on the bottom of the mixer. Also one scroll bar under the nav button "part settings" on the left side. Just above 16 buttons for parts. It has only gray track but scroll bar should be visible if there are more than 16 channels. It should work with mouse scrolling when mouse is over box, so there is no problem with it size.

![asset 1](https://cloud.githubusercontent.com/assets/3619927/20780737/b0d91174-b77d-11e6-98df-760513a58ead.png)

That little colored rectangle on left side is indicator. Because user need to know is he changing instrument from parts or kit editor instrument. User still have possibility to compile new zyn-fusion with more than 16 channels? There are also scroll bar under kit editor and addsynth. Same question.

I have a question about that button QWERTY on the bottom. Is that drop down button? I don't see zxcv knob. I need to know is that knob missing or it will not be there, this affect on design so I need to adapt.

On the top I put small button with midi keyboard icon, purpose of this button is to turn on and off keyboard section on the bottom. If this is not going to be there at all I will remove this from designs. I see some labels name are changed (like midi, learn, fine, nrp) this is good if this will stay there like that I would change this on my designs also, please I need to know. I don't see icon for record this part is I believe in development?
I've put word panic in panic button. Is it redundant?

**Comment by budislav** [comment]
In the meantime

![mixer_new](https://cloud.githubusercontent.com/assets/3619927/20783426/2115d902-b794-11e6-8061-e787d580bad3.png)

**Comment by fundamental** [comment]
On 11-30, Budislav wrote:
> @fundamental thank you for asking me for this. Since I designed everything, it is good (necessary) to ask me for help with every UX/UI change. I will try to make this good but I have some questions about UI.
> 
> In the old Zyn we could compile synth with more than 16 channels. That's why I put scroll bar on the bottom of the mixer. Also one scroll bar under the nav button "part settings" on the left side. Just above 16 buttons for parts. It has only gray track but scroll bar should be visible if there are more than 16 channels. 
> 
> ![asset 1](https://cloud.githubusercontent.com/assets/3619927/20780737/b0d91174-b77d-11e6-98df-760513a58ead.png)
> 
> That little colored rectangle on left side is indicator. Because user need to know is he changing instrument from parts or kit editor instrument. User still have possibility to compile new zyn-fusion with more than 16 channels? There are also scroll bar under kit editor and addsynth. Same question.
It's possible to compile with more than 16 channels, but in my total
involvement with zynaddsubfx I think there's only been 2 instances where
I've observed people maintaining a copy with different numbers of
voices/parts/effects than default.

This may be added back in in the future, but it's a relatively minor
oversight compared to some of the other differences from the mockups.

> I have a question about that button QWERTY on the bottom.
> Is that drop down button?
It is, though the other keyboard layouts aren't completely implemented.
Right now I just have to figure out what the non-ascii keycodes are
getting mapped to, and then the dropdown should be available showing the
different options and working with other keyboard layout types.

> I don't see zxcv knob.
> I need to know is that knob missing or it will not be there, this affect on design so I need to adapt.
I personally don't see that knob as a major bit of functionality, so I
chose to remove it.

> On the top I put small button with midi keyboard icon, purpose of this button is to turn on and off keyboard section on the bottom.
> If this is not going to be there at all I will remove this from designs.
At the moment it's not in the implementation, but I would like to
eventually add it.

> I see some labels name are changed (like midi, learn, fine, nrp) this
> is good if this will stay there like that I would change this on my
> designs also, please I need to know.
They're likely going to stay similar to what I have up, though
midi/learn will likely change into "midi learn"/acquire.


> I don't see icon for record this part is I believe in development?
At the moment recording can be started from within the File menu.
That was the quickest to implement, but I'd say the more polished
workflow is:
1. Showing [record, pause, play] when not in recording mode
2. Clicking any of them when recording isn't active launches the file
   browser
3. Showing [stop, pause, play] when in recording mode
4. Transitioning back to non-recording mode after hitting stop

So, it's fair to consider that still in development.

> I've put word panic in panic button. Is it redundant?
It felt like it was redundant when had it briefly in the implementation.

**Comment by budislav** [comment]
@fundamental thanks on all answers!

> It's possible to compile with more than 16 channels, but in my total
involvement with zynaddsubfx I think there's only been 2 instances where
I've observed people maintaining a copy with different numbers of
voices/parts/effects than default.
This may be added back in in the future, but it's a relatively minor
oversight compared to some of the other differences from the mockups.

Ok, but voice list looks totally different with only 8 voices. Can you add 8 more voices in adsynth to be by default, or I will need to do some changes it can stay like that.

> It is, though the other keyboard layouts aren't completely implemented.
Right now I just have to figure out what the non-ascii keycodes are
getting mapped to, and then the dropdown should be available showing the
different options and working with other keyboard layout types.

Ok, but I think this should be somewhere in settings, because user will set this only once, right? So there is no need for that to be visible all time.

**Comment by fundamental** [comment]
On 12-04, Budislav wrote:
> Ok, but voice list looks totally different with only 8 voices.
> Can you add 8 more voices in adsynth to be by default, or I will need to do some changes it can stay like that.
I'm currently not planning on adding support for 8+ voices into the UI

> > It is, though the other keyboard layouts aren't completely implemented.
> Right now I just have to figure out what the non-ascii keycodes are
> getting mapped to, and then the dropdown should be available showing the
> different options and working with other keyboard layout types.
> 
> Ok, but I think this should be somewhere in settings, because user will set this only once, right?
> So there is no need for that to be visible all time.
Yeah, that sounds pretty reasonable.
The whole settings view still needs to be sketched out, but once it's in
the UI I'm fine with moving this dropdown to there.
